// tools/convert-stores.mjs
import fs from "node:fs";
import path from "node:path";
import YAML from "yaml";

const ROOT = process.cwd();
const inPath = path.join(ROOT, "stores.yaml");
const outPath = path.join(ROOT, "src", "data", "stores711.ts");

function die(msg) {
  console.error("❌ " + msg);
  process.exit(1);
}

if (!fs.existsSync(inPath)) die(`找不到 stores.yaml：${inPath}`);

let raw = fs.readFileSync(inPath, "utf8");

// ✅ 容錯：從第一個合法 key 開始（例如 '110817':）
const m = raw.match(/^\s*'\d+'\s*:/m);
if (!m || m.index == null) die("stores.yaml 內找不到形如 '110817': 的資料段落");

raw = raw.slice(m.index);

let parsed;
try {
  parsed = YAML.parse(raw);
} catch (e) {
  die("YAML 解析失敗，請確認 stores.yaml 格式正確（例如縮排、冒號）。\n" + String(e));
}

if (!parsed || typeof parsed !== "object") die("YAML 解析結果不是物件，無法轉換");

const rows = [];
for (const [id, v] of Object.entries(parsed)) {
  const no = String(id).replace(/'/g, "").trim();
  const storeName = (v && typeof v === "object" && (v.store || v.name)) ? String(v.store || v.name) : "";
  const address = (v && typeof v === "object" && v.address) ? String(v.address) : "";
  if (!no || !storeName || !address) continue;

  rows.push({ storeId: no, name: storeName, address });
}

if (rows.length === 0) die("轉換結果為 0 筆。請確認 stores.yaml 內容是否完整、且每筆都有 store / address。");

const out = `// AUTO-GENERATED by tools/convert-stores.mjs
export type Store711 = {
  storeId: string
  name: string
  address: string
}

export const STORES_711: Store711[] = ${JSON.stringify(rows, null, 2)}
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out, "utf8");

console.log("✅ 已輸出：", outPath);
console.log("✅ 筆數：", rows.length);
